### ISSUE TITLE
Error on c2tcp server and client app

### ISSUE THREAD

**Issue by limlynn** [Soheil-ab/c2tcp#4]
Hello, with your kind guide, I built kernel 4.13.1 with your patch(linux-4-13-1-orca-c2tcp-0521.patch) and tried to run server and client app.

I set the server machine with this settings
```
sudo sysctl -w  net.ipv4.tcp_c2tcp_enable=1  # enable c2tcp
sudo sysctl -w net.ipv4.tcp_no_metrics_save=1 # disable tcp cache
sudo su
echo 0 > /sys/module/tcp_cubic/parameters/hystart  # disable tcp hystart
exit

sudo sysctl -w -q net.ipv4.tcp_low_latency=1
sudo sysctl -w -q net.ipv4.tcp_autocorking=0
sudo sysctl -w -q net.ipv4.tcp_no_metrics_save=1
sudo sysctl -w -q net.ipv4.ip_forward=0 # no using mahimahi

```

And, I've got this error. 
```
$ sudo ./server 9001 0 150 100
[start_server] cubic
[start_server] Server is Connected to the client...
testing
[DataThread] Server is sending the traffic ...
[server-standalone.cc-CntThread-298] setsockopt: for index:0 flow_index:1 ... Protocol not available (ret1:-1)
```

Do I have to set the kernel of client machine same as the server? 
I didn't install the kernel on client machine

**Comment by Soheil-ab** [comment]
Hi @limlynn,
Thanks for the comment.  The definitions of a parameter (C2TCP_ALPHA) in the new Kernel and the new Application were not synchronized and that made your Error. It is now resolved. 

For the record, you only need to patch the Kernel on the Sender side. You still can enable ipv4.ip_forward (even though you don't use Mahimahi).

BTW, it seems that the GitHub's notifications are not working properly, because I didn't get notification regarding your comment. plz next time mention me directly by @Soheil-ab in your comments. This is a more reliable way!

**Comment by lim5g** [comment]
@Soheil-ab Thank you so much. Now I am running c2tcp. Thank you. BTW, I couldn't check any udp packet (tcpdump -n udp -p 9001), but I saw a lot of tcp packet with your code(tcpdump -p 9001). Did I see it correctly?

**Comment by Soheil-ab** [comment]
@lim5g, np. 

Correct, C2TCP is a TCP Plug-In. So, you are really sending TCP packets if you are using it {on your chosen port though}.
