### ISSUE TITLE
No value for avg_urtt.

### ISSUE THREAD

**Issue by YongchangHu** [Soheil-ab/c2tcp#5]
Dear Soheil,
We have tried the C2tcp. Though we keep getting avg_urtt = 0 at the followings. 
https://github.com/Soheil-ab/c2tcp/blob/7b84c91d468468eddd3056bf52b80ec254353bb3/src/server-standalone.cc#L264

Our plot shows:
avg_urtt:0 min_rtt:30814 cnt:0,avg_thr:0,thr_cnt:0,cwnd:18,pacing_rate:856164
min_rtt get non-zero value though.

BTW, why does C2tcp use deepcc struct, when there is tcp_c2tcp_info in define.h？

Yongchang

**Comment by Soheil-ab** [comment]
Hey @YongchangHu,

A few things first?
- What is the Kernel (output of <uname -r>) you are using? 
- Did you change the Kernel patch?
- Are you using the latest code (there were a few updates about two month ago)?

Assuming you haven't modified kernel and you are using the latest code, the line that you showed tells that no ACK packet has been received in the previous 0.5s report interval (parameter "cnt" shows the number of ACKs received in previous timeslot). The minrtt that you are seeing is the global minrtt from the beginning of the connection till the time of report, but avg_rtt is only average value of RTTs during the reported timeslot. Having a valid minrtt means that you at least have seen one Ack packet. That one Ack could have been there longtime ago though! 

That might be OK depending on your test scenario. So, let me know what is the network scenario you are using for test, then we can continue investigating the likely reasons. 
Also, please send me a record of all these lines from the beginning till the end (every 0.5 second C2TCP pulls a new report from Kernel and you can have a new line of info).

Regarding the deepcc struct:
Actually, I have merged the code/kernel of three schemes named DeepCC (under Review!), Orca (Sigcomm'20), and C2TCP (JSAC'19). The current structure is a general structure in the new merged Kernel which can also be used by C2TCP to pull useful information from the Kernel. So, you can see deepcc struct just as a more general structure for pulling info. Since the Kernel Patch file is public, you can directly check how deepcc struct is created and filled therein.

**Comment by YongchangHu** [comment]
Thanks.  We have solved the problems. It is because there is no ack in the last 0.5s.
Let us close this issue.

Yongchang
