### ISSUE TITLE
Lack .ko files when doing modules_install in the compiling process

### ISSUE THREAD

**Issue by PeterSH6** [Soheil-ab/c2tcp#8]
Sorry about interrupting again.
I tried to compile my own kernel following your guide in the **c2tcp-IFID repo** and I successfully compiled it using `sudo make -j4`. However, when I run `sudo make modules_install`, it warns me that it couldn't find **xxx.ko** files(which are all compiled into .o files). I was stuck in the step and don't really not how to solve this problem.

**Comment by Soheil-ab** [comment]
Hey @PeterSH6 

Would you plz share the exact error? Just as a general comment, please make sure that you have installed required packages to compile a kernel. something like below:

sudo apt-get install build-essential libncurses-dev bison flex libssl-dev libelf-dev

**Comment by PeterSH6** [comment]
Hey @Soheil-ab 

`sudo apt-get install build-essential libncurses-dev bison flex libssl-dev libelf-dev` after doing this I compile it again and finally I see the version 4.13.1 !!! Thanks a lot!!!

But new issues come😢, I found that the new kernel can't connect to the Internet. It seems that I miss some drivers. What's more, when running your `./run-sample.sh`, it got this kinds of bugs and the svg picture is broken.
<img width="1147" alt="截屏2020-12-09 下午4 42 27" src="https://user-images.githubusercontent.com/43173188/101605783-901a7080-3a3d-11eb-9774-f839c2ce42ac.png">
<img width="1149" alt="截屏2020-12-09 下午4 42 34" src="https://user-images.githubusercontent.com/43173188/101605793-927cca80-3a3d-11eb-95d2-69c0861c3ae7.png">

**Comment by Soheil-ab** [comment]
Hey @PeterSH6 

It's good to see that you managed to compile your Kernel! 

Regarding your problems:

1) I assume that you use WIFI to connect to Internet. The issue is that you haven't compiled your pc/laptop's WIFI driver when you compiled the Kernel. If you don't know the exact driver that you need to compile, there is a simple way to resolve that (and other future Driver issues). You can first install Ubuntu 16.04 on the same machine. Then make a copy of the /boot/config-* file therein. You need to paste this file on the folder where you compile your kernel (The destination name should be ".config"). After compiling your Kernel using the new .config file, your driver issues will vanish!

2) The things that you observe on the attached pictures are not bugs actually! The server/client process will be killed after the duration of the trace file (or your desired time). So all the lines indicating Mahimahi is killed should be there! The only issue in your case is that you are using the latest Mahimahi version I assume. They have added a few changes compared to the time I used their code! One change is that they now keep the record of dropped packets in the final file. The mm-throughput-graph-modified script need to first parse the final file to generate the corresponding results. Line 114 in that script indicates that the script observes a line with "d" type (meaning packet is dropped). 

I have already updated the script to support parsing the dropped packets! You can pull again to use it.

**Comment by PeterSH6** [comment]
Hey @Soheil-ab 

Thanks for your update and reading your latest commit make me realize what's wrong!

Concerning to the first question, I didn't use WIFI but Ethernet. I found that although I compile the kernel with the same config file in my machine, it couldn't find the Internet Device when boot with the kernel 4.13.1. I solve this problem by downloading a file in this link [e1000e](https://downloadcenter.intel.com/zh-cn/download/15817?_ga=1.159975677.114505945.1484457019) and then copy it into `/usr/local/src/e1000E`. Then enter `cd /usr/local/src/e1000e-x.x.x/src/` and type `make install` and `modprobe e1000e`. And the Ethernet Driver is installed.

**Comment by Soheil-ab** [comment]
Hey @PeterSH6 

Happy to hear that :-)
